# Generated by Django 4.1.3 on 2022-12-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('houseaddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderName', models.CharField(max_length=50)),
                ('senderEmail', models.EmailField(max_length=50)),
                ('senderContact', models.CharField(max_length=20)),
                ('senderLocation', models.CharField(max_length=20)),
                ('trackingId', models.CharField(max_length=15)),
                ('receiverName', models.CharField(max_length=50)),
                ('receiverEmail', models.EmailField(max_length=50)),
                ('receiverContact', models.CharField(max_length=20)),
                ('receiverLocation', models.CharField(max_length=20)),
                ('deliveryDate', models.DateTimeField(auto_now=True)),
                ('duedate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
